sudo: required
dist: trusty

language: cpp

compiler:
- gcc

before_install:
- sudo apt-get -qq update
- sudo apt-get install -qq libsfml-dev
- sudo apt-get install -qq libgtest-dev
- sudo apt-get install -qq lcov
- sudo apt-get install -qq ruby
- gem install coveralls-lcov

install:
# Build GTest
- "cd /usr/src/gtest && sudo cmake -DBUILD_SHARED_LIBS=ON . && sudo cmake --build . && sudo cp libgtest* /usr/local/lib ; cd -"

before_script:
# Start X Virtual Framebuffer
- "export DISPLAY=:99.0 ; sh -e /etc/init.d/xvfb start ; sleep 3"

script:
- cd ${TRAVIS_BUILD_DIR}
- cmake -DCMAKE_BUILD_TYPE=TestCoverage -DCOVERALLS_TOKEN=${COVERALLS_TOKEN} -DBUILD_DOC=OFF .
- make test-coverage
